In [1]:
import pandas as pd

In [3]:
df1=pd.read_csv('/content/City.csv')

In [4]:
df1.head()

,City,Ratings,Ideal_duration,Best_time_to_visit,City_desc
0,Manali,4.5,2-4,October-June,[' One of the most popular hill stations in Hi...
1,Leh Ladakh,4.6,5-7,JulyOctober,"["" Ladakh is a union territory in the Kashmir ..."
2,Coorg,4.2,2-3,September-June,[' Located amidst imposing mountains in Karnat...
3,Andaman,4.5,4-6,October-March,[' Replete with turquoise blue water beaches a...
4,Lakshadweep,4.0,4-6,September-February,"["" Formerly known as Laccadive Islands, Laksha..."

In [5]:
df2=pd.read_csv('/content/Places.csv')

In [6]:
df2.head()

,City,Place,Ratings,Distance,Place_desc
0,Manali,1. Capture the Sceneries of Old Manali,3.9,2 km from city center,On the other side of the Manalsu river is a p...
1,Manali,2. Engage in the Adventures of Solang Valley,4.6,8 km from city center,Solang Valley is one of the most popular tour...
2,Manali,3. Jogini Waterfall,4.6,4 km from city center,Jogini Waterfall is located about 3 kilometre...
3,Manali,4. Hadimba Temple,4.4,1 km from city center,"Hadimba temple, away from the hustle and bust..."
4,Manali,5. Rohtang Pass,4.4,16 km from city center,Rohtang pass is the stretch which connects Ma...

In [7]:
merged_df = pd.merge(df1, df2, on='City')
display(merged_df.head())

,City,Ratings_x,Ideal_duration,Best_time_to_visit,City_desc,Place,Ratings_y,Distance,Place_desc
0,Manali,4.5,2-4,October-June,[' One of the most popular hill stations in Hi...,1. Capture the Sceneries of Old Manali,3.9,2 km from city center,On the other side of the Manalsu river is a p...
1,Manali,4.5,2-4,October-June,[' One of the most popular hill stations in Hi...,2. Engage in the Adventures of Solang Valley,4.6,8 km from city center,Solang Valley is one of the most popular tour...
2,Manali,4.5,2-4,October-June,[' One of the most popular hill stations in Hi...,3. Jogini Waterfall,4.6,4 km from city center,Jogini Waterfall is located about 3 kilometre...
3,Manali,4.5,2-4,October-June,[' One of the most popular hill stations in Hi...,4. Hadimba Temple,4.4,1 km from city center,"Hadimba temple, away from the hustle and bust..."
4,Manali,4.5,2-4,October-June,[' One of the most popular hill stations in Hi...,5. Rohtang Pass,4.4,16 km from city center,Rohtang pass is the stretch which connects Ma...

In [8]:
import numpy as np

def extract_months(time_str):
    if pd.isna(time_str):
        return []
    months = []
    time_str = time_str.replace(' ', '')
    time_parts = time_str.split(',')
    for part in time_parts:
        if '-' in part:
            start_month, end_month = part.split('-')
            months.append(start_month)
            months.append(end_month)
        else:
            months.append(part)
    return months

merged_df['Months'] = merged_df['Best_time_to_visit'].apply(extract_months)
display(merged_df.head())

,City,Ratings_x,Ideal_duration,Best_time_to_visit,City_desc,Place,Ratings_y,Distance,Place_desc,Months
0,Manali,4.5,2-4,October-June,[' One of the most popular hill stations in Hi...,1. Capture the Sceneries of Old Manali,3.9,2 km from city center,On the other side of the Manalsu river is a p...,"[October, June]"
1,Manali,4.5,2-4,October-June,[' One of the most popular hill stations in Hi...,2. Engage in the Adventures of Solang Valley,4.6,8 km from city center,Solang Valley is one of the most popular tour...,"[October, June]"
2,Manali,4.5,2-4,October-June,[' One of the most popular hill stations in Hi...,3. Jogini Waterfall,4.6,4 km from city center,Jogini Waterfall is located about 3 kilometre...,"[October, June]"
3,Manali,4.5,2-4,October-June,[' One of the most popular hill stations in Hi...,4. Hadimba Temple,4.4,1 km from city center,"Hadimba temple, away from the hustle and bust...","[October, June]"
4,Manali,4.5,2-4,October-June,[' One of the most popular hill stations in Hi...,5. Rohtang Pass,4.4,16 km from city center,Rohtang pass is the stretch which connects Ma...,"[October, June]"

In [9]:
best_cities_by_month = {}

for index, row in merged_df.iterrows():
    city = row['City']
    months = row['Months']
    for month in months:
        if month not in best_cities_by_month:
            best_cities_by_month[month] = []
        if city not in best_cities_by_month[month]:
            best_cities_by_month[month].append(city)

print(best_cities_by_month)

{'October': ['Manali', 'Andaman', 'Udaipur', 'Srinagar', 'Mcleodganj', 'Ooty', 'Kodaikanal', 'Varanasi', 'Mumbai', 'Amritsar', 'Wayanad', 'Haridwar', 'Kasol'], 'June': ['Manali', 'Coorg', 'Mcleodganj', 'Shimla', 'Ooty', 'Kodaikanal', 'Kasol'], 'JulyOctober': ['Leh Ladakh'], 'September': ['Coorg', 'Lakshadweep', 'Munnar', 'Tirupati'], 'March': ['Andaman', 'Udaipur', 'Munnar', 'Shimla', 'Jaipur', 'Varanasi', 'Amritsar', 'Nashik', 'Tirupati'], 'February': ['Lakshadweep', 'Goa', 'Alleppey', 'Mumbai', 'Haridwar', 'Mahabaleshwar'], 'November': ['Goa', 'Jaipur'], 'April': ['Srinagar'], 'SeptemberJune': ['Rishikesh'], '': ['Alleppey', 'Dharamshala'], 'OctoberMarch': ['Delhi'], 'May': ['Wayanad'], 'December': ['Mahabaleshwar'], 'July': ['Nashik']}

In [10]:
print(best_cities_by_month.keys())

def recommend_by_month(month):
    if month in best_cities_by_month:
        return f"Cities recommended for {month}: {', '.join(best_cities_by_month[month])}"
    else:
        return f"No recommendations available for {month}. Please enter a valid month."

month_input = input("Enter the month for which you want recommendations (e.g., October, June): ")
# Based on the keys, convert the input to match the format
month_input_formatted = month_input.title() # Start with title, adjust if needed after seeing keys
recommendations = recommend_by_month(month_input_formatted)
print(recommendations)

dict_keys(['October', 'June', 'JulyOctober', 'September', 'March', 'February', 'November', 'April', 'SeptemberJune', '', 'OctoberMarch', 'May', 'December', 'July'])
Enter the month for which you want recommendations (e.g., October, June): March
Cities recommended for March: Andaman, Udaipur, Munnar, Shimla, Jaipur, Varanasi, Amritsar, Nashik, Tirupati

In [11]:
def extract_duration(duration_str):
    if pd.isna(duration_str):
        return (np.nan, np.nan)
    parts = str(duration_str).split('-')
    if len(parts) == 1:
        duration = int(parts[0])
        return (duration, duration)
    elif len(parts) == 2:
        return (int(parts[0]), int(parts[1]))
    else:
        return (np.nan, np.nan)

merged_df[['Min_duration', 'Max_duration']] = merged_df['Ideal_duration'].apply(extract_duration).tolist()

display(merged_df.head())

,City,Ratings_x,Ideal_duration,Best_time_to_visit,City_desc,Place,Ratings_y,Distance,Place_desc,Months,Min_duration,Max_duration
0,Manali,4.5,2-4,October-June,[' One of the most popular hill stations in Hi...,1. Capture the Sceneries of Old Manali,3.9,2 km from city center,On the other side of the Manalsu river is a p...,"[October, June]",2,4
1,Manali,4.5,2-4,October-June,[' One of the most popular hill stations in Hi...,2. Engage in the Adventures of Solang Valley,4.6,8 km from city center,Solang Valley is one of the most popular tour...,"[October, June]",2,4
2,Manali,4.5,2-4,October-June,[' One of the most popular hill stations in Hi...,3. Jogini Waterfall,4.6,4 km from city center,Jogini Waterfall is located about 3 kilometre...,"[October, June]",2,4
3,Manali,4.5,2-4,October-June,[' One of the most popular hill stations in Hi...,4. Hadimba Temple,4.4,1 km from city center,"Hadimba temple, away from the hustle and bust...","[October, June]",2,4
4,Manali,4.5,2-4,October-June,[' One of the most popular hill stations in Hi...,5. Rohtang Pass,4.4,16 km from city center,Rohtang pass is the stretch which connects Ma...,"[October, June]",2,4

In [12]:
def recommend_by_month_and_duration(month, duration):
    recommended_cities = []
    for index, row in merged_df.iterrows():
        months = row['Months']
        min_duration = row['Min_duration']
        max_duration = row['Max_duration']
        city = row['City']

        if month in months:
            if not pd.isna(min_duration) and not pd.isna(max_duration):
                if min_duration <= duration <= max_duration:
                    if city not in recommended_cities:
                        recommended_cities.append(city)
            elif pd.isna(min_duration) and pd.isna(max_duration):
                # Handle cases where duration is not specified, maybe recommend if month matches?
                # For now, we'll skip if duration info is missing
                pass


    if recommended_cities:
        return f"Cities recommended for {month} with a duration of {duration} days: {', '.join(recommended_cities)}"
    else:
        return f"No recommendations found for {month} with a duration of {duration} days."

# Example usage (optional, for testing)
# print(recommend_by_month_and_duration('October', 3))
# print(recommend_by_month_and_duration('March', 5))
# print(recommend_by_month_and_duration('July', 2))

In [17]:
month_input = input("Enter the desired month (e.g., October, June): ")
duration_input_str = input("Enter the desired trip duration as a single number of days (e.g., 3): ")
duration_input = int(duration_input_str)

print(f"You entered month: {month_input}")
print(f"You entered duration: {duration_input} days")

Enter the desired month (e.g., October, June): June
Enter the desired trip duration as a single number of days (e.g., 3): 2
You entered month: June
You entered duration: 2 days

In [18]:
recommendations = recommend_by_month_and_duration(month_input, duration_input)
print(recommendations)

Cities recommended for June with a duration of 2 days: Manali, Coorg, Mcleodganj, Shimla, Ooty, Kodaikanal, Kasol

In [29]:
def recommend_by_month_and_duration(month, duration, sort_by_rating=True):
    recommended_cities_data = []
    for index, row in merged_df.iterrows():
        months = row['Months']
        min_duration = row['Min_duration']
        max_duration = row['Max_duration']
        city = row['City']
        rating = row['Ratings_x']

        if month in months:
            if not pd.isna(min_duration) and not pd.isna(max_duration):
                if min_duration <= duration <= max_duration:
                    recommended_cities_data.append({'City': city, 'Rating': rating})
            elif pd.isna(min_duration) and pd.isna(max_duration):
                pass # Skipping cities with missing duration data

    # Remove duplicate cities while keeping the highest rating if duplicates exist
    unique_cities = {}
    for city_data in recommended_cities_data:
        city = city_data['City']
        rating = city_data['Rating']
        if city not in unique_cities or unique_cities[city]['Rating'] < rating:
            unique_cities[city] = city_data

    recommended_cities_list = list(unique_cities.values())

    if sort_by_rating:
        recommended_cities_list.sort(key=lambda x: x['Rating'], reverse=True)

    if recommended_cities_list:
        city_strings = [f"{city['City']} ({city['Rating']})" for city in recommended_cities_list]
        return f"Cities recommended for {month} with a duration of {duration} days (sorted by rating): {', '.join(city_strings)}"
    else:
        return f"No recommendations found for {month} with a duration of {duration} days."

recommendations = recommend_by_month_and_duration(month_input, duration_input)
print(recommendations)

Cities recommended for June with a duration of 2 days (sorted by rating): Manali (4.5), Mcleodganj (4.4), Kodaikanal (4.4), Kasol (4.4), Ooty (4.3), Coorg (4.2), Shimla (4.2)

In [30]:
import pickle

# Define the filename for the pickle file
pickle_filename = 'merged_df.pkl'

# Save the merged_df DataFrame to a pickle file
with open(pickle_filename, 'wb') as f:
    pickle.dump(merged_df, f)

print(f"'{pickle_filename}' created successfully.")

'merged_df.pkl' created successfully.

In [31]:
import pickle

with open("merged_df.pkl", "rb") as f:
    df = pickle.load(f)

print(type(df))
print(df.shape)
print(df.head())

<class 'pandas.core.frame.DataFrame'>
(2989, 12)
     City  Ratings_x Ideal_duration Best_time_to_visit  \
0  Manali        4.5            2-4       October-June
1  Manali        4.5            2-4       October-June
2  Manali        4.5            2-4       October-June
3  Manali        4.5            2-4       October-June
4  Manali        4.5            2-4       October-June

                                           City_desc  \
0  [' One of the most popular hill stations in Hi...
1  [' One of the most popular hill stations in Hi...
2  [' One of the most popular hill stations in Hi...
3  [' One of the most popular hill stations in Hi...
4  [' One of the most popular hill stations in Hi...

                                            Place  Ratings_y  \
0         1. Capture the Sceneries of Old Manali         3.9
1   2. Engage in the Adventures of Solang Valley         4.6
2                            3. Jogini Waterfall         4.6
3                              4. Hadimba Temple         4.4
4                                5. Rohtang Pass         4.4

                    Distance  \
0    2 km  from city center
1    8 km  from city center
2    4 km  from city center
3    1 km  from city center
4   16 km  from city center

                                          Place_desc           Months  \
0   On the other side of the Manalsu river is a p...  [October, June]
1   Solang Valley is one of the most popular tour...  [October, June]
2   Jogini Waterfall is located about 3 kilometre...  [October, June]
3   Hadimba temple, away from the hustle and bust...  [October, June]
4   Rohtang pass is the stretch which connects Ma...  [October, June]

   Min_duration  Max_duration
0             2             4
1             2             4
2             2             4
3             2             4
4             2             4

In [32]:
import pickle, pandas as pd

with open("merged_df.pkl", "rb") as f:
    df = pickle.load(f)

# Test if your "Place" column works
print(df["Place"].head())
print(df[df["Place"].str.contains("Manali", case=False, na=False)])

0           1. Capture the Sceneries of Old Manali
1     2. Engage in the Adventures of Solang Valley
2                              3. Jogini Waterfall
3                                4. Hadimba Temple
4                                  5. Rohtang Pass
Name: Place, dtype: object
      City  Ratings_x Ideal_duration Best_time_to_visit  \
0   Manali        4.5            2-4       October-June
32  Manali        4.5            2-4       October-June
46  Manali        4.5            2-4       October-June
47  Manali        4.5            2-4       October-June

                                            City_desc  \
0   [' One of the most popular hill stations in Hi...
32  [' One of the most popular hill stations in Hi...
46  [' One of the most popular hill stations in Hi...
47  [' One of the most popular hill stations in Hi...

                                             Place  Ratings_y  \
0          1. Capture the Sceneries of Old Manali         3.9
32   33. Explore the Wildlife at Manali Sanctuary         3.9
46                          47. Zorbing in Manali         NaN
47                     48. Winter Carnival Manali         NaN

                                     Distance  \
0                     2 km  from city center
32                    1 km  from city center
46                    9 km  from city center
47   48 out of 50  places to visit in Manali

                                           Place_desc           Months  \
0    On the other side of the Manalsu river is a p...  [October, June]
32   Manali Sanctuary is home to Mona- the state b...  [October, June]
46   Zorbing is a fun hill-sport in this region th...  [October, June]
47   The Manali Winter Carnival is Himachal Prades...  [October, June]

    Min_duration  Max_duration
0              2             4
32             2             4
46             2             4
47             2             4

In [35]:
# create_pickle.py
import pandas as pd
import pickle
import re

# Step 1: Load your CSV (or existing DataFrame)
df = merged_df  # replace with your CSV file if you have

# Step 2: Clean 'Place' column (remove numbering like "1. Place Name")
df["Place_clean"] = df["Place"].apply(lambda x: re.sub(r'^\d+\.\s*', '', str(x)))

# Step 3: Convert 'City_desc' and 'Place_desc' from list-like strings to plain text
df["City_desc"] = df["City_desc"].apply(lambda x: str(x).strip("[]'"))
df["Place_desc"] = df["Place_desc"].apply(lambda x: str(x).strip("[]'"))

# Step 4: Fill NaN values
df = df.fillna("")

# Step 5: Save cleaned DataFrame as pickle
with open("pickle.pkl", "wb") as f:
    pickle.dump(df, f)

print("✅ Pickle file 'merged_df.pkl' created successfully!")

✅ Pickle file 'merged_df.pkl' created successfully!

In [36]:
import pickle, pandas as pd

with open("merged_df.pkl", "rb") as f:
    df = pickle.load(f)

# Test if your "Place" column works
print(df["Place"].head())
print(df[df["Place"].str.contains("Manali", case=False, na=False)])

0           1. Capture the Sceneries of Old Manali
1     2. Engage in the Adventures of Solang Valley
2                              3. Jogini Waterfall
3                                4. Hadimba Temple
4                                  5. Rohtang Pass
Name: Place, dtype: object
      City  Ratings_x Ideal_duration Best_time_to_visit  \
0   Manali        4.5            2-4       October-June
32  Manali        4.5            2-4       October-June
46  Manali        4.5            2-4       October-June
47  Manali        4.5            2-4       October-June

                                            City_desc  \
0    One of the most popular hill stations in Hima...
32   One of the most popular hill stations in Hima...
46   One of the most popular hill stations in Hima...
47   One of the most popular hill stations in Hima...

                                             Place Ratings_y  \
0          1. Capture the Sceneries of Old Manali        3.9
32   33. Explore the Wildlife at Manali Sanctuary        3.9
46                          47. Zorbing in Manali
47                     48. Winter Carnival Manali

                                     Distance  \
0                     2 km  from city center
32                    1 km  from city center
46                    9 km  from city center
47   48 out of 50  places to visit in Manali

                                           Place_desc           Months  \
0    On the other side of the Manalsu river is a p...  [October, June]
32   Manali Sanctuary is home to Mona- the state b...  [October, June]
46   Zorbing is a fun hill-sport in this region th...  [October, June]
47   The Manali Winter Carnival is Himachal Prades...  [October, June]

    Min_duration  Max_duration                                     Place_clean
0              2             4         1. Capture the Sceneries of Old Manali
32             2             4   33. Explore the Wildlife at Manali Sanctuary
46             2             4                          47. Zorbing in Manali
47             2             4                     48. Winter Carnival Manali